ui/webview/analysis.js
ui/webview/index.d.ts
ui/webview/webview-Android.js

- added displayZoomControls option for Webview in Android

[NTVE-170] displayZoomControls option for Webview in Android

---

ui/floatingmenu/floatingmenu-Android.js
ui/tabbarcontroller/tabbarcontroller-Android.js
ui/view/view-Android.js

Yoga version updated. Refactor the usages.

[NTVE-262] change YogaNode creation based on new version

---

application/analysis.js
application/application-Android.js
application/application-iOS.js
application/index.d.ts

- add Application.canOpenUrl function

Story/ntve 300 canOpenUrl

---

ui/materialtextbox/analysis.js
ui/materialtextbox/index.d.ts
ui/materialtextbox/materialtextbox-Android.js
ui/materialtextbox/materialtextbox-iOS.js

- add expandsOnOverflow property for iOS
- add maxLines property for Android

[NTVE-261] add expandsOnOverflow and maxLines

---

ui/imageview/imageview-Android.js

[NTVE-311] handle the error case in glide

---

ui/searchview/searchview-Android.js

use TextWatcher instead of QueryListener in SearchView

[NTVE-277] use TextWatcher instead of QueryListener

---

ui/headerbar/index.d.ts
ui/page/page-Android.js

- contentInsetStartWithNavigation
- padding

[NTVE-192] make properties optional

---

ui/bottomtabbar/bottomtabbar-iOS.js
ui/navigationcontroller/navigationcontroller-iOS.js

[NTVE-398]: fix background color issues related to Xcode-13.1 version upgrade.

[NTVE-398]: fix background color issues related to Xcode-13.1

---

ui/imageview/imageview-Android.js

fix issuse that fetchFromUrl parameters are not optional

[NTVE-464] fix fetchFromUrl parameters issue

---

ui/imageview/imageview-Android.js

fix the fetchFromUrl fails if no onFailure method is defined

[NTVE-554] fix fetchFromUrl parameter issue

---

src/global/blob/blob.android.ts
src/global/blob/blob.ios.ts
src/global/blob/blob.ts

Refactored and made slice android only. Still it throws error on write, @jhalitaksoy will look into that.

blob refactor & slice android only

---

src/ui/switch/switch.android.ts

- Fixed thumbOnColor, thumbOffColor, toggleOnColor and toggleOffColor issues
- Use native feature for thumbOnColor, thumbOffColor, toggleOnColor and toggleOffColor.

[NTVE-823] fix: thumb and track color issues in switch

---

.types/missings-ios.d.ts
src/ui/label/label.ios.ts
src/ui/view/view.ios.ts
src/ui/viewgroup/viewgroup.ios.ts

applyLayout

---

src/ui/flexlayout/flexlayout.android.ts
src/ui/view/view.android.ts

improve the performance by removing checks. dispatcher already does the check.

delete oldValue and newValue checks

---

src/device/hardware/hardware.ts
src/device/network/network.ts

- Hardware.android.IMEI
- Hardware.android.vendorID
- Network.IMEI

[FW-917]: deprecate IMEI and vendorID

---

src/ui/view/view.android.ts
src/ui/view/view.ios.ts
src/ui/view/view.ts

- add shadowColor property to view
- deprecate view.ios.shadowColor

Story/fw 972 add shadowColor property to view

---

src/ui/view/view.ios.ts

[FW-957]: every corner needs to be calculated in order to draw its container

[FW-957]: every corner needs to be calculated in order to draw its container

---

src/ui/shared/Flex.ts
src/ui/shared/android/nativeflexprops.ts
src/ui/shared/ios/nativeflexprops.ts
src/ui/shared/ios/yogaenums.ts

- SPACE_EVENLY (JustifyContent)
- WRAP_REVERSE (FlexWrap)
- BASELINE (AlignContent)
- SPACE_BETWEEN (AlignContent)
- SPACE_AROUND (AlignContent)

Story/fw 843 - missing flex properties

---

src/ui/page/page.android.ts

fix: SwipeView brokes dismiss button if initialized on onLoad

[FW-721] fix SwipeView issue in modal page

---

src/ui/view/view.ios.ts

calculate individual radiuses with shadow, background color, border and border color

[FW-992]: calculate individual radiuses with shadow, background color, border and border color

---

src/ui/tabbaritem/tabbaritem.ios.ts

We may need to revert this check after understand the real cause of the issue @furkanarabaci

tabbar crashes when try to create via context

---

src/ui/bottomsheet/bottomsheet.android.ts

- check isShowing before show the bottomsheet
- fix lifecyle issues

[FW-1107]: fix bottomsheet issues

---

src/ui/bottomtabbar/bottomtabbar.android.ts

fix: Cannot set empty-title in BottomTabbarItem

[FW-1175]: fix BottomTabbarItem title issue

---

src/device/permission/permission.android.ts
src/device/permission/permission.ts

- fix type issue in requestPermission
- fix promise issue in android.requestPermissions
- change location group behaviour

[FW-1193]: fix New Permission API issues

---

src/ui/videoview/videoview-events.ts
src/ui/videoview/videoview.ts

add description for fullscreen feature in VideoView

[FW-1209]: update tsdoc in VideoView

---

src/ui/view/view.android.ts
src/ui/view/view.ts

add individual border properties on Android
- borderTopLeftRadius
- borderTopRightRadius
- borderTopStartRadius
- borderTopEndRadius
- borderBottomLeftRadius
- borderBottomRightRadius
- borderBottomStartRadius
- borderBottomEndRadius

[FW-1430] add individual border properties on Android
